# Generated by Django 3.1.2 on 2020-10-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_code_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='codezeilen',
            new_name='name',
        ),
    ]
