# Generated by Django 3.1.2 on 2020-10-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_auto_20201026_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='content',
            field=models.FileField(upload_to=None),
        ),
    ]
