# Generated by Django 3.1.2 on 2020-10-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0005_auto_20201026_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='content',
            field=models.FileField(upload_to='codes/uploads/'),
        ),
    ]
